// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Anchor from "../../Components/Anchor/Anchor.bs.js";

function s(prim) {
  return prim;
}

function Index(props) {
  return React.createElement("div", {
              className: "flex flex-col justify-center space-y-10"
            }, React.createElement("section", {
                  className: "flex-1 space-y-5"
                }, React.createElement("h1", {
                      className: "text-3xl font-bold underline"
                    }, "Boas vindas aos meus slides!"), React.createElement("p", {
                      className: "text-xl"
                    }, "Se voce esta aqui, provavelmente assistiu a alguma palestra minha e ta\n      procurando por slides!")), React.createElement("section", {
                  className: "space-y-5"
                }, React.createElement("p", undefined, "Estao todos disponiveis no github rodando o comando `npm run dev`\n      depois de clonar o repo!"), React.createElement("ol", undefined, React.createElement("li", undefined, React.createElement(Anchor.make, {
                              children: "1 - A Cabeca do Open Source",
                              href: "https://github.com/bragamat/ihaveslides/blob/main/gurusp-2023-02-11/slides.md"
                            })))));
}

var make = Index;

export {
  s ,
  make ,
}
/* react Not a pure module */
