// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Default from "../Layouts/Default.bs.js";

function make(props) {
  var content = React.createElement(props.Component, props.pageProps);
  return React.createElement(Default.Layout.make, {
              children: content
            });
}

export {
  make ,
}
/* react Not a pure module */
