// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Anchor(props) {
  return React.createElement("a", {
              className: "rounded-md bg-indigo-600 py-1.5 px-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
              href: props.href
            }, props.children);
}

var make = Anchor;

export {
  make ,
}
/* react Not a pure module */
