// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cypress from "../../../bindings/Cypress/Cypress.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

Cypress.describe("Root path", (function (param) {
        Cypress.it("/", (function (param) {
                cy.visit("/", undefined);
                cy.contains(undefined, "Boas vindas aos meus slides!", undefined);
                cy.contains(undefined, "Se voce esta aqui, provavelmente assistiu a alguma\n    palestra minha", undefined);
                (function (param, param$1) {
                      return cy.contains(undefined, "Click aqui e da uma olhada!", param !== undefined ? Caml_option.valFromOption(param) : undefined);
                    }).click(undefined);
              }));
      }));

export {
  
}
/*  Not a pure module */
