// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Default$Layout(props) {
  return React.createElement("main", {
              className: "w-full h-full sm:flex justify-center items-center dark:bg-black dark:text-white"
            }, props.children);
}

var Layout = {
  make: Default$Layout
};

export {
  Layout ,
}
/* react Not a pure module */
